repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimfiler'
depends = 'unite.vim'
hook_add = '''
    source ~/.config/nvim/plugins/vimfiler.rc.vim

    autocmd Filetype vimfiler nmap <buffer>  <CR>   <Plug>(vimfiler_expand_or_edit)
    autocmd Filetype vimfiler nmap <buffer>  l      <Plug>(vimfiler_expand_or_edit)
    autocmd Filetype vimfiler nmap <buffer>  <C-l>  <Plug>(vimfiler_cd_or_edit)
    autocmd FileType vimfiler setl nobl

    let g:vimfiler_as_default_explorer = 1
    let g:vimfiler_tree_opened_icon    = '↩ '
    let g:vimfiler_tree_closed_icon    = '↪ '
    let g:vimfiler_tree_leaf_icon      = " "

    let g:vimfiler_file_icon           = '- '
    let g:vimfiler_marked_file_icon    = '✓ '
    let g:vimfiler_readonly_file_icon  = '✗ '
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]] # color
repo = 'tomasr/molokai'
hook_add = '''
    set background=dark
    au MyAuto VimEnter * nested colorscheme molokai
'''

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # elm syntax
repo = 'ElmCast/elm-vim'
on_ft = 'elm'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
    \   'colorscheme': 'wombat'
    \}
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd   ctermbg=54
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven  ctermbg=23
    let g:indent_guides_enable_on_vim_startup=1
    let g:indent_guides_guide_size=1
'''

[[plugins]]
repo = 'kassio/neoterm'
if = "has('nvim')"
hook_add = '''
    nnoremap <silent> ,rc :TREPLSendFile<cr>
    nnoremap <silent> ,rl :TREPLSendLine<cr>
    nnoremap <silent> vt  :Ttoggle<cr>
    nnoremap <silent> vs  :terminal<cr>
    vnoremap <silent> ,rl :TREPLSendSelection<cr>
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'justincampbell/vim-eighties'
hook_add = '''
    let g:eighties_enable = 1
    let g:eighties_minimum_width = 110
    let g:eighties_exta_width = 0
    let g:eighties_compute = 1
'''

[[plugins]]
repo = 'LeafCage/yankround.vim'

 [[plugins]]
repo = 'junegunn/vim-emoji'
hook_add = '''
    let g:gitgutter_sign_added = emoji#for('small_blue_diamond')
    let g:gitgutter_sign_modified = emoji#for('small_orange_diamond')
    let g:gitgutter_sign_removed = emoji#for('small_red_triangle')
    let g:gitgutter_sign_modified_removed = emoji#for('collision')
    set completefunc=emoji#complete
'''

[[plugins]]
repo = 'rhysd/github-complete.vim'

[[plugins]]
repo = 'osyo-manga/vim-brightest'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
    let g:EasyMotion_do_mapping = 0
    let g:EasyMotion_enter_jump_first = 1
    map  f  <Plug>(easymotion-fl)
    map  F  <Plug>(easymotion-Fl)
    nmap t  <Plug>(easymotion-s2)
    xmap t  <Plug>(easymotion-s2)
    omap t  <Plug>(easymotion-s2)
    nmap g/ <Plug>(easymotion-sn)
    xmap g/ <Plug>(easymotion-sn)
    omap g/ <Plug>(easymotion-tn)
'''

