# 基本設定
set-option -g default-shell $SHELL
set-option -g default-terminal "screen-256color"
set -g terminal-overrides 'xterm:colors=256'

# プレフィックスキー
set -g prefix C-q
unbind C-b

# ペイン分割
bind | split-window -h
bind - split-window -v

# インデックス
set-option -g base-index 1
set-window-option -g pane-base-index 1

# ステータスバー
set-option -g status-justify centre
set-option -g status-bg "colour238"
set-option -g status-fg "colour255"

# ペイン操作
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# マウス
set-option -g mouse on

# コピーモード
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
